TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsReverseEngineerScaffolder.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/Helpers/TempDirectory.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

Resolve #23 NullReferenceException in CheckOutputFiles.
- Refactor tests to create scaffolder separately.
- Extend ReverseEngineerScaffolder to allow saving of entities without a DbContext.

Fix Null Reference Exception when Saving Entities without a DbContext

---

src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

Refactor AddHandlebarsScaffolding to regisgter IHbsHelperService. Refactor AddHandlebarsHelpers to get IHbsHelperService before adding helpers.

Register IHbsHelperService in AddHandlebarsScaffolding.

---

README.md
sample/ScaffoldingSample/CodeTemplates/CSharpDbContext/DbContext.hbs
sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs
sample/ScaffoldingSample/Contexts/NorthwindSlimContextExt.cs
sample/ScaffoldingSample/Models/Country.cs
sample/ScaffoldingSample/Models/Customer.cs
sample/ScaffoldingSample/Models/Employee.cs
sample/ScaffoldingSample/Sample.ReadMe.md
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs

- Update sample to implement partial method to convert a property from string to an enum.

Add OnModelCreatingExt partial method to generated DbContext (fixes #29)

---

README.md
sample/ScaffoldingSample/Sample.ReadMe.md
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsHelperService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/Helpers/HandlebarsHelpers.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IHbsHelperService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/Fakes/TestProviderCodeGenerator.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

Change `context` argument type to `Dictionary<string, object>` so that model metadata is easier to use in helper methods.

Make context argument of Handlebars helper method strongly typed

---

test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/HbsTypeScriptScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

Register `IHbsBlockHelperService` in unit tests.

Fix unit tests after adding support for Handlebars block helpers.

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs

Fix for issue where OnModelCreating is generating modelBuilder lines with the un-transformed EntityType names.

Update HbsCSharpDbContextGenerator to emit transformed entityType.Name.

---

src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Class.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Class.hbs
test/Scaffolding.Handlebars.Tests/EmbeddedResourceTemplateFileServiceTests.ExpectedTemplates.cs
test/Scaffolding.Handlebars.Tests/ExpectedEntities.cs
test/Scaffolding.Handlebars.Tests/FileSystemTemplateFileServiceTests.ExpectedTemplates.cs

In this PR I did the followings (see issue #107):

DataAnnotation: Usage of nameof in ForeignKeyAttribute/InversePropertyAttribute

---

src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Class.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/TypeScriptEntityType/Class.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/TypeScriptEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Class.hbs
test/Scaffolding.Handlebars.Tests/Contexts/NorthwindDbContext.cs
test/Scaffolding.Handlebars.Tests/EmbeddedResourceTemplateFileServiceTests.ExpectedTemplates.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedEntities.cs
test/Scaffolding.Handlebars.Tests/ExpectedTypeScriptContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedTypeScriptInterfaces.cs
test/Scaffolding.Handlebars.Tests/FileSystemTemplateFileServiceTests.ExpectedTemplates.cs

**Proposed changes**
Two new handlebars tokens were added to allow for the use of {{comment}} on table templates and {{property-comment}} on property templates. This can be useful to incorporate database description metadata into XML doc comments on the models.
**Related Issue**
There isn't an associated issue at this time.

Support for schema comments

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IEntityTypeTransformationService.cs

This PR fix issue #98, includes all the fixes made by dmayhak and discussed in PR #102 including author requested changes, and completes it with some more fixes.
In order to reproduce the additional issues I've found, run the sample with the followings:
```c#
services.AddHandlebarsTransformers(
entityNameTransformer: n => n == "CustomerSetting" ? "Setting" : n,
entityFileNameTransformer: n => n,
constructorTransformer: e => e.PropertyType == "CustomerSetting" ? new EntityPropertyInfo("Setting", e.PropertyName + "Foo") : e,
propertyTransformer: e => e.PropertyName == "Setting" ? new EntityPropertyInfo(e.PropertyType, "Value") :
e.PropertyName == "Country" ? new EntityPropertyInfo("Country", e.PropertyName, false) : e,
navPropertyTransformer: e => e.PropertyType == "CustomerSetting" ? new …
```

Handlebars Transformers Issues

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs

Fix NullReferenceException with EntityTypeTransformationService.TransformNavPropertyName
Fixes #136.

Fix NullReferenceException with EntityTypeTransformationService.TransformNavPropertyName

---

src/EntityFrameworkCore.Scaffolding.Handlebars/IModelExtensions.cs
test/Scaffolding.Handlebars.Tests/IModelExtensionsTests.cs

With the .NET 5 updates, views were no longer being excluded using the ExcludedTables option.  I updated `IModelExtensions` to use GetViewName() and GetViewSchema() in addition to the table methods.
**Put `Closes #XXXX` in your comment**
Closes #149
**Additional Resources**
- [RelationalEntityTypeExtensions.GetViewName(IEntityType) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalentitytypeextensions.getviewname?view=efcore-5.0#Microsoft_EntityFrameworkCore_RelationalEntityTypeExtensions_GetViewName_Microsoft_EntityFrameworkCore_Metadata_IEntityType_)
- [RelationalEntityTypeExtensions.GetViewSchema(IEntityType) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalentitytypee …

Fixed ExcludedTables option to also include views, as it did previously.

---

src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
test/Scaffolding.Handlebars.Tests/ExpectedEntities.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs

- Add an initially failing test for navigation properties that should be nullable
- Infer navigation property nullability from whether or not the association foreign key is required
- Extend the code generation in GenerateNavigationProperties to account for navigation property nullable
- Emit a nav-property-isnullable variable for use in Handlebars scripts
**Put `Closes #XXXX` in your comment**
Closes #151 
**Additional Resources**
Refer to the [Contributing Guidelines](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/.github/CONTRIBUTING.md) for this project.

Fix issues associated with nullable navigation properties

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs

This PR aims to fix issues surrounding namespaces/schemas when using the EnableSchemaFolders option.
Included fixes:
- Fixed usings that were required by navigation properties not being added to the entity type code.
- Fixed using the wrong namespace alias when generating fluent code for foreign keys between schemas.
Closes #134

EnableSchemaFolders Import/Qualification Fixes

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs

When `EnableSchemaFolders` is enabled the generated `EntityTypeName` is incorrect for a view's schema. Instead we check if the entity is a table or schema and generate the correct schema name accordingly.

EntityTypeName and Schema for View Fixes

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

Fix encoding issue by setting Handlebars NoEscape to `true`.
Closes #30.

Set Handlebars NoEscape to True

---

README.md
sample/ScaffoldingSample.TypeScript/CodeTemplates/TypeScriptDbContext/Partials/DbConstructor.hbs
sample/ScaffoldingSample.TypeScript/CodeTemplates/TypeScriptDbContext/Partials/DbImports.hbs
sample/ScaffoldingSample.TypeScript/CodeTemplates/TypeScriptDbContext/Partials/DbOnConfiguring.hbs
sample/ScaffoldingSample.TypeScript/CodeTemplates/TypeScriptDbContext/Partials/DbSets.hbs
sample/ScaffoldingSample.TypeScript/CodeTemplates/TypeScriptEntityType/Partials/Properties.hbs
sample/ScaffoldingSample.TypeScript/Models/Category.ts
sample/ScaffoldingSample.TypeScript/Models/Employee.ts
sample/ScaffoldingSample.TypeScript/Models/EmployeeTerritory.ts
sample/ScaffoldingSample.TypeScript/Models/Territory.ts
sample/ScaffoldingSample.TypeScript/ScaffoldingDesignTimeServices.cs
sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/TypeScriptEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HandlebarsScaffoldingOptions.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs

Fix GenerateImports in TypeScript entity generator.
Update version to 6.0.0-preview2.
Makes it possible to upgrade from v5 to v6 without re-creating templates.

Remove skip-nav-properties from Properties.hbs.

---

sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

This PR allows access to entity type from transform functions.
Example of use : rename all primary keys ‘TableNameId’ to ‘Id’
`
services.AddHandlebarsTransformers(propertyTransformer: (e, p) => 
$"{e.Name}Id" == p.PropertyName ? 
new EntityPropertyInfo(p.PropertyType, "Id", false) : 
new EntityPropertyInfo(p.PropertyType, p.PropertyName, p.PropertyIsNullable));
`

Access IEntityType from transform functions

---

sample/ScaffoldingSample.Api/ScaffoldingSample.Api.csproj
sample/ScaffoldingSample.Embedded/ScaffoldingSample.Embedded.csproj
sample/ScaffoldingSample.TypeScript/ScaffoldingSample.TypeScript.csproj
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.targets
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs

Correct problem with files not found.
- Change package path from contentFiles to lib/net6.0

Change package path from contentFiles to lib/net6.0

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedEntities.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/Helpers/HandlebarsTransformers.cs

When using Transform mappings, and UseDataAnnotations=false, provide .ToTable and .HasColumnName methods in the generated context when table and column names are different to the entity and property names.
When using Transform mappings, and UseDataAnnotations=true, use ColumnAttribute in generated entities and do not use .ToTable and .HasColumnName methods in the context. 
Closes #188.

Add .ToTable and .HasColumnName methods when using Transforms

---

README.md
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

Rename overloaded `AddHandlebarsTransformers` to `AddHandlebarsTransformers2`.
Update `HbsCSharpEntityTypeGenerator.GenerateForeignKeyAttribute` to avoid generating FK attribute when key has been transformed.
Closes #201.

Fix ambiguous method AddHandlebarsTransformers

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
test/Scaffolding.Handlebars.Tests/Contexts/NorthwindDbContext.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedTypeScriptContexts.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/HbsTypeScriptScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/Helpers/Constants.cs
test/Scaffolding.Handlebars.Tests/Helpers/HandlebarsTransformers.cs
test/Scaffolding.Handlebars.Tests/Models/Customer.cs

Add HasHey to context when key is non-conventional.
Closes #203.

[Fix] HasKey Reference Left Out with Non-Conventional Key Property

---

src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityPropertyInfo.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationServiceBase.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/Internal/EntityTypeExtensions.cs

Moved IsManyToManyJoinEntityType extension class. Use IsManyToManyJoinEntityType to prevent InverseProperty and ForeignKey Annotations from being generated in Virtual Tables.
Closes #240

Moved IsManyToManyJoinEntityType extension class

---

src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityPropertyInfo.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationServiceBase.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/Internal/EntityTypeExtensions.cs

Added Enum support documented in this Question #242.
Closes #242
Closes #244

Added Enum features for default in DBContext and Class generation.
