src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/FileSystemTemplateFileService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsDbContextTemplateService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTemplateService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTemplateService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ITemplateFileService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/InMemoryTemplateFileService.cs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpDbContext/DbContext.hbs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpDbContext/Partials/DbImports.hbs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpDbContext/Partials/DbSets.hbs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Class.hbs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Partials/Constructor.hbs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Partials/Imports.hbs
test/Scaffolding.Handlebars.Tests/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
test/Scaffolding.Handlebars.Tests/ExpectedTemplates.cs
test/Scaffolding.Handlebars.Tests/FileSystemTemplateFileServiceTests.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/Helpers/Constants.cs
test/Scaffolding.Handlebars.Tests/Scaffolding.Handlebars.Tests.csproj

- Use project templates if they exist.
- Copy templates to project if missing.

Include code templates in scaffolding library.

---

README.md
sample/ScaffoldingSample/CodeTemplates/CSharpDbContext/Partials/DbSets.hbs
sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Class.hbs
sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs
sample/ScaffoldingSample/Models/Category.cs
sample/ScaffoldingSample/Models/Customer.cs
sample/ScaffoldingSample/Models/CustomerSetting.cs
sample/ScaffoldingSample/Models/Employee.cs
sample/ScaffoldingSample/Models/EmployeeTerritories.cs
sample/ScaffoldingSample/Models/Order.cs
sample/ScaffoldingSample/Models/OrderDetail.cs
sample/ScaffoldingSample/Models/Product.cs
sample/ScaffoldingSample/Models/Territory.cs
sample/ScaffoldingSample/Sample.ReadMe.md
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsHelperService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTemplateService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/Helpers/HandlebarsHelpers.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IHbsHelperService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IHbsTemplateService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

Add support for registering Handlebars helpers.

---

sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ReverseEngineerOptions.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

- Reaname namespace to Microsoft.EntityFrameworkCore.Design.

Rename ServiceCollectionExtensions namespace.

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/Scaffolding.Handlebars.Tests.csproj

All tests are passing - I need this for EF Core 2.2 support in EF Core Power Tools

Update to EF Core 2.2

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs

Update `HbsCSharpDbContextGenerator` and `HbsCSharpEntityTypeGenerator` to change visibility of private members to protected.

Change generators private members to protected (fixes #43)

---

sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityPropertyInfo.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

Create `AddHandlebarsTransformers` method accepting transform functions for customizing generated entities.

Entity Type Transformers

---

sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

Update AddHandlebarsScaffolding to include Handlebars "spaces" helper.

Fix AddHandlebarsScaffolding

---

sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
sample/ScaffoldingSample/Models/Category.cs
sample/ScaffoldingSample/Models/Customer.cs
sample/ScaffoldingSample/Models/CustomerSetting.cs
sample/ScaffoldingSample/Models/Employee.cs
sample/ScaffoldingSample/Models/EmployeeTerritories.cs
sample/ScaffoldingSample/Models/Order.cs
sample/ScaffoldingSample/Models/OrderDetail.cs
sample/ScaffoldingSample/Models/Product.cs
sample/ScaffoldingSample/Models/Territory.cs
sample/ScaffoldingSample/Sample.ReadMe.md
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsBlockHelperService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IHbsBlockHelperService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

following our discussion in this [issue](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/70)

Added Handlebars Block helpers support

---

sample/ScaffoldingSample.Api/ScaffoldingSample.Api.csproj
sample/ScaffoldingSample.TypeScript/ScaffoldingSample.TypeScript.csproj
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedTypeScriptContexts.cs
test/Scaffolding.Handlebars.Tests/Scaffolding.Handlebars.Tests.csproj

Update all NuGet packages to latest versions for .NET Core 2.2.

Update Nuget packages to latest.

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HandlebarsScaffoldingOptions.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HumanizerPluralizer.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedEntities.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs

This PR superseeds PR #109 adding a Pluralization service implemented with Humanizer package.

Pluralization Implementation using Humanizer

---

README.md
sample/ScaffoldingSample/CodeTemplates/CSharpDbContext/Partials/DbSets.hbs
sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Class.hbs
sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs
sample/ScaffoldingSample/Models/Category.cs
sample/ScaffoldingSample/Models/Customer.cs
sample/ScaffoldingSample/Models/CustomerSetting.cs
sample/ScaffoldingSample/Models/Employee.cs
sample/ScaffoldingSample/Models/Order.cs
sample/ScaffoldingSample/Models/OrderDetail.cs
sample/ScaffoldingSample/Models/Product.cs
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpDbContext/Partials/DbSets.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityPropertyInfo.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HandlebarsScaffoldingOptions.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs
test/Scaffolding.Handlebars.Tests/ExpectedContexts.cs
test/Scaffolding.Handlebars.Tests/ExpectedTypeScriptContexts.cs
test/Scaffolding.Handlebars.Tests/HbsTypeScriptScaffoldingGeneratorTests.cs

@feature/support for c# nullable projects #101

---

EntityFrameworkCore.Scaffolding.Handlebars.sln
README.md
sample/ScaffoldingSample.Api/ScaffoldingSample.Api.csproj
sample/ScaffoldingSample.Embedded/ScaffoldingSample.Embedded.csproj
sample/ScaffoldingSample.TypeScript/ScaffoldingSample.TypeScript.csproj
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
test/Scaffolding.Handlebars.Tests/Scaffolding.Handlebars.Tests.csproj

Update to NET Core 3.1 SDK

---

README.md
sample/ScaffoldingSample/CodeTemplates/CSharpDbContext/Partials/DbImports.hbs
sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs
sample/ScaffoldingSample/Contexts/NorthwindSlimContextPartial.cs
sample/ScaffoldingSample/Models/dbo/Category.cs
sample/ScaffoldingSample/Models/dbo/Customer.cs
sample/ScaffoldingSample/Models/dbo/CustomerSetting.cs
sample/ScaffoldingSample/Models/dbo/Employee.cs
sample/ScaffoldingSample/Models/dbo/Order.cs
sample/ScaffoldingSample/Models/dbo/OrderDetail.cs
sample/ScaffoldingSample/Models/dbo/Product.cs
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpDbContext/Partials/DbImports.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpDbContextGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsEntityTypeTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptEntityTypeGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IEntityTypeTransformationService.cs

Fix namespace issues when schema folders are enabled
Closes issue #121.
Replaced PR #119.
Thanks to @audacity76 for issue and preliminary PR.

Fix Namespace Issues When Schema Folders Are Enabled

---

sample/ScaffoldingSample.Api/ScaffoldingSample.Api.csproj
sample/ScaffoldingSample.Embedded/ScaffoldingSample.Embedded.csproj
sample/ScaffoldingSample.TypeScript/ScaffoldingSample.TypeScript.csproj
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
test/Scaffolding.Handlebars.Tests/Scaffolding.Handlebars.Tests.csproj

Update EF Core packages to v3.1.6.

Update EF Core packages to v3.1.6

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsContextTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/IContextTransformationService.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/HbsTypeScriptScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

I added contextFileNameTransformer and HbsContextTransformationService / IContextTransformationService.
I also added some tests but I'm not sure it should be done like this.
Closes #141

Customize context file name, add contextFileNameTransformer

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

- Resolve IContextTransformationService.
- Do not remove DbOnConfiguring.hbs.
**Put `Closes #XXXX` in your comment**
Closes #145

[Fix] Resolve IContextTransformationService

---

sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Class.hbs
sample/ScaffoldingSample/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs
sample/ScaffoldingSample/Sample.ReadMe.md
sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Class.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpEntityType/Partials/Properties.hbs
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HandlebarsScaffoldingOptions.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs

Generate multi-line comments.
Allow disabling of generated comments.
**Put `Closes #XXXX` in your comment**
Closes #144

Support Line Characters in Generated Comments

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs

Closes #176 Schema names added without enabling schema folders.

Fix #176: Schema names added without enabling schema folders

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs

Revert v5.0.5-preview1

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.targets

Add msbuild target file to copy CodeTemplates folder to output.
Closes #186

Copy CodeTemplates folder from NuGet package to output directory on build

---

src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpEntityTypeGenerator.cs

Fix missing FK data annotation on skip nav properties.

Fix missing FK data annotation on skip nav properties

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs
test/Scaffolding.Handlebars.Tests/CSharpEntityTypeAlt/Class.hbs
test/Scaffolding.Handlebars.Tests/CSharpEntityTypeAlt/Partials/Constructor.hbs
test/Scaffolding.Handlebars.Tests/CSharpEntityTypeAlt/Partials/Imports.hbs
test/Scaffolding.Handlebars.Tests/CSharpEntityTypeAlt/Partials/Properties.hbs
test/Scaffolding.Handlebars.Tests/ExpectedEntities.cs
test/Scaffolding.Handlebars.Tests/Fakes/FakeCSharpTemplateLanguageService.cs
test/Scaffolding.Handlebars.Tests/HbsCSharpScaffoldingGeneratorTests.cs
test/Scaffolding.Handlebars.Tests/ReverseEngineeringConfigurationTests.cs

- Add failing test: WriteCode_Should_Generate_Entity_Files_No_Encoding
- Update Handlebars.Net package to make test pass.
- Waiting for [Handlebars.Net PR 477](https://github.com/Handlebars-Net/Handlebars.Net/pull/477) to be included in next release.
Closes #30.
Closes #184.

Fix Handlebars Encoding Issue

---

src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj

Update package version to 7.0.0

---

README.md
sample/ScaffoldingSample.Embedded/ScaffoldingSample.Embedded.csproj
sample/ScaffoldingSample.TypeScript/ScaffoldingSample.TypeScript.csproj
sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs
sample/ScaffoldingSample/ScaffoldingSample.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/EntityFrameworkCore.Scaffolding.Handlebars.csproj
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsCSharpModelGenerator.cs
src/EntityFrameworkCore.Scaffolding.Handlebars/HbsTypeScriptModelGenerator.cs
test/Scaffolding.Handlebars.Tests/Scaffolding.Handlebars.Tests.csproj

Upgrade to EF Core 9.0
Closes #246

Upgrade to EF Core 9.0
